SELECT DISTINCT C.CAR_ID, C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * (100 - COALESCE(P.DISCOUNT_RATE, 0)) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID=H.CAR_ID
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
    AND C.CAR_ID NOT IN(
        SELECT C.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE C.CAR_ID = H.CAR_ID 
            AND (H.END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
            OR H.START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
            OR (H.END_DATE > '2022-11-30') AND (H.START_DATE < '2022-11-01'))
    )
    AND (C.DAILY_FEE * (100 - COALESCE(P.DISCOUNT_RATE, 0)) / 100 * 30) >= 500000
    AND (C.DAILY_FEE * (100 - COALESCE(P.DISCOUNT_RATE, 0)) / 100 * 30) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC