SELECT C.CAR_ID, C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * (100 - COALESCE(P.DISCOUNT_RATE, 0)) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'
    )
HAVING (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC