-- 코드를 입력하세요
WITH CAR_MONTHLY AS (
    SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID, MONTH(START_DATE)
)

SELECT MONTH, CAR_ID, RECORDS
FROM CAR_MONTHLY 
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_MONTHLY
    GROUP BY CAR_ID
    HAVING SUM(RECORDS) >= 5
)
ORDER BY MONTH, CAR_ID DESC