-- 코드를 작성해주세요
WITH MAX_LENGTH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
JOIN MAX_LENGTH AS M
    ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.LENGTH
JOIN FISH_NAME_INFO AS N 
    ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY I.ID